/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestNative */

#ifndef _Included_TestNative
#define _Included_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestNative
 * Method:    CopyWAVFileAddEffect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_TestNative_CopyWAVFileAddEffect
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
